language: node_js
node_js:
  - '4.4'

env:
  - CXX=g++-4.8

addons:
  ssh_known_hosts: $PUBLISH_URL
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - sshpass

sudo: true

before_script:
  - npm install -g gulp

script: 
  - gulp build
  - gulp ssh:create

after_success:
  - ls build_v*.zip
  - sshpass -p $PUBLISH_PASSWORD scp -o ChallengeResponseAuthentication=no -o CheckHostIP=no -q build_v*.zip $PUBLISH_USER@$PUBLISH_URL:$PUBLISH_PATH

after_failure:
  - cat /home/travis/Axodoss/Ceramic/npm-debug.log

branches:
  only: master

notifications:
  email: false
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

cache:
  directories:
    - node_modules
    - report