language: node_js
node_js:
  - '4.4'

compiler: clang-3.6
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8

sudo: true

before_install:
  

before_script:
  - npm install

script: 
  - gulp build

after_failure:
  - cat /home/travis/build/NathanWalker/angular2-seed-advanced/npm-debug.log

branches:
  only: master

notifications:
  email: true
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
  global:
    # https://github.com/DefinitelyTyped/tsd#tsdrc
    # Token has no scope (read-only access to public information)
    #- TSD_GITHUB_TOKEN=51b0c1347cfd8c2c90ba0f60db7898171cbb17c8

cache:
  directories: node_modules