language: node_js
node_js:
  - '4.4'

env:
  - CXX=g++-4.8

addons:
  ssh_known_hosts: $PUBLISHER_URL
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - openssh-client

sudo: true

before_script:
  - npm install -g gulp

script: 
  - gulp build
  - gulp publish

after_failure:
  - cat /home/travis/Axodoss/Ceramic/npm-debug.log

branches:
  only: master

notifications:
  email: false
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
  global:
    # https://github.com/DefinitelyTyped/tsd#tsdrc
    # Token has no scope (read-only access to public information)
    #- TSD_GITHUB_TOKEN=51b0c1347cfd8...

cache:
  directories:
    - node_modules
    - report